name: docker-build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}
      - uses: jemand771/docker-build-action@main
        with:
          images: |
            ${{ secrets.NEXUS_HOST }}/bauprojekt
          GITHUB_TOKEN: ${{ github.token }}
          push_strategy: push
          platforms: linux/amd64
